language: node_js
node_js:
  - stable

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - yarn install

script:
  - yarn bundle
  - yarn test
  - yarn doc
  - touch ./docs/.nojekyll

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT


deploy:
  local_dir: docs
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master